site_name: Godot Material Icons
repo_url: https://github.com/rakugoteam/Godot-Material-Icons

extra:
  homepage: https://rakugoteam.github.io
  version:
    provider: mike
  alternate:
    - name: English
      link: /
      lang: en

theme:
  name: material
  logo: assets/logo.svg
  palette:
    scheme: slate
    primary: deep purple
  features:
    - navigation.instant
    - navigation.indexes

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
